const randomArray = {
    "escaped": [
        'Thanks partner',
        'I thought I was a gonner',
        'mighty fine of ya',
        `congrats, you don't suck`,
        'deepest graditude',
        'I got away with murder, Yay!',
        'ride easy partner',
        'yippie skippie',
    ],
    "wrongGuess": [
        `It's a good day to die`,
        'ouch',
        'smh',
        `where's the rest of me?`,
        `I'm innocent`,
        `it wasn't me, it was the one armed man`,
        'you got the wrong guy',
        `don't I get a phone call first?`,
        `just kill me already`,
        'get it over with already',
    ],
    "rightGuess": [
        'about dang time',
        'yes, do more of that',
        `hurry, running out of time`,
        'lucky guess',
        'yay, not as bad as I thought',
    ],
    "hangmanCharacters": [
        "./img/hangman1.png",
        "./img/hangman2.png",
    ],
    "commonWords": [
        "apple",
        "beach",
        "table",
        "party",
        "swift",
        "sweet",
        "smile",
        "space",
        "swim",
        "swift",
        "sound",
        "taste",
        "super",
        "quick",
        "quiet",
        "speak",
        "start",
        "peace",
        "horse",
        "music",
        "ocean",
        "laugh",
        "light",
        "love",
        "angel",
        "brown",
        "black",
        "blue",
        "clock",
        "count",
        "dance",
        "drink",
        "drive",
        "eagle",
        "earth",
        "flower",
        "friend",
        "green",
        "heart",
        "house",
        "image",
        "index",
        "jazz",
        "jungle",
        "kind",
        "king",
        "laugh",
        "listen",
        "money",
        "month",
        "night",
        "ocean",
        "orange",
        "paper",
        "peace",
        "peace",
        "piano",
        "place",
        "plant",
        "point",
        "queen",
        "rain",
        "river",
        "road",
        "robot",
        "rock",
        "school",
        "shirt",
        "shoe",
        "shop",
        "show",
        "sister",
        "sleep",
        "smile",
        "sport",
        "star",
        "storm",
        "street",
        "sun",
        "sweet",
        "swim",
        "table",
        "teach",
        "team",
        "tennis",
        "test",
        "thank",
        "think",
        "train",
        "travel",
        "tree",
        "union",
        "urban",
        "user",
        "video",
        "visit",
        "voice",
        "walk",
        "water",
        "week",
        "white",
        "woman",
        "world",
        "write",
        "yellow",
    ],
}


const getRandom = (obj) => {
    const arr = randomArray[obj]
    return arr[Math.floor(Math.random() * arr.length)]
}

export default getRandom;



